{ ****************************************************************** }
{                                                                    }
{   VCL component TFactoring                                         }
{                                                                    }
{   Factoring                                                        }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file c:\eletro guerra\classe\principal\factoring.cd }
{   on 31 Oct 2003 at 8:15                                           }
{                                                                    }
{   Copyright © 1999 by SOFTECH                                      }
{                                                                    }
{ ****************************************************************** }

unit TFactoring;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls, 
     Forms, Graphics, Squery, Dbtables, Dialogs, Db, Stdctrls, 
     Mask, Dbctrls, Configuracao, Dbgrids, Windows, Funcoes, 
     Variants;

type
  TFactoring = class(TSQuery)
    private
      { Private fields of TFactoring }
        { Storage for property AgenciaNumero }
        FAgenciaNumero : String;
        { Storage for property ChequeCNC }
        FChequeCNC : Integer;
        { Storage for property CodigoFCT }
        FCodigoFCT : Integer;
        { Storage for property CodigoIFC }
        FCodigoIFC : Integer;
        { Storage for property DataAlterado }
        FDataAlterado : TDateTime;
        { Storage for property DataCadastro }
        FDataCadastro : TDateTime;
        { Storage for property EAgenciaNumero }
        FEAgenciaNumero : TMaskEdit;
        { Storage for property EChequeCNC }
        FEChequeCNC : TEdit;
        { Storage for property ECodigoFCT }
        FECodigoFCT : TEdit;
        { Storage for property ECodigoIFC }
        FECodigoIFC : TEdit;
        { Storage for property EDataAlterado }
        FEDataAlterado : TMaskEdit;
        { Storage for property EDataCadastro }
        FEDataCadastro : TMaskEdit;
        { Storage for property EOBS }
        FEOBS : TEdit;
        { Storage for property ESituacao }
        FESituacao : TComboBox;
        { Storage for property EValor }
        FEValor : TEdit;
        { Storage for property MaquinaIFC }
        FMaquinaIFC : Integer;
        { Storage for property OBS }
        FOBS : String;
        { Storage for property Situacao }
        FSituacao : Integer;
        { Storage for property Valor }
        FValor : Double;

      { Private methods of TFactoring }
        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;
        { Read method for property AgenciaNumero }
        function GetAgenciaNumero : String;
        { Read method for property ChequeCNC }
        function GetChequeCNC : Integer;
        { Read method for property CodigoFCT }
        function GetCodigoFCT : Integer;
        { Read method for property CodigoIFC }
        function GetCodigoIFC : Integer;
        { Read method for property DataAlterado }
        function GetDataAlterado : TDateTime;
        { Read method for property DataCadastro }
        function GetDataCadastro : TDateTime;
        { Read method for property MaquinaIFC }
        function GetMaquinaIFC : Integer;
        { Read method for property OBS }
        function GetOBS : String;
        { Read method for property Situacao }
        function GetSituacao : Integer;
        { Read method for property Valor }
        function GetValor : Double;

    protected
      { Protected fields of TFactoring }

      { Protected methods of TFactoring }
        { Resets prop of component type if referenced component deleted }
        procedure Notification(AComponent : TComponent; Operation : TOperation); override;

    public
      { Public fields and properties of TFactoring }

      { Public methods of TFactoring }
        function AlterarAuto:Boolean;
        procedure AtualizaControles(Habilitar:Boolean);
        procedure CancelaEdicao;
        procedure CarregaDados;
        constructor Create(AOwner: TComponent); override;
        destructor Destroy; override;
        function FinalizaEdicao:Boolean;
        function InserirAuto:Boolean;
        procedure LimpaCampos;
        { Localiza um Grau }
        function LocalizarCod(CdCNC,CdFCT:Integer):Boolean;
        procedure PreparaAlteracao;
        procedure PreparaInsercao;
        function deletarauto:Boolean;

    published
      { Published properties of TFactoring }
        property AgenciaNumero : String
             read GetAgenciaNumero write FAgenciaNumero;
        property ChequeCNC : Integer read GetChequeCNC write FChequeCNC;
        property CodigoFCT : Integer read GetCodigoFCT write FCodigoFCT;
        property CodigoIFC : Integer read GetCodigoIFC write FCodigoIFC;
        property DataAlterado : TDateTime
             read GetDataAlterado write FDataAlterado;
        property DataCadastro : TDateTime
             read GetDataCadastro write FDataCadastro;
        property EAgenciaNumero : TMaskEdit
             read FEAgenciaNumero write FEAgenciaNumero;
        property EChequeCNC : TEdit read FEChequeCNC write FEChequeCNC;
        property ECodigoFCT : TEdit read FECodigoFCT write FECodigoFCT;
        property ECodigoIFC : TEdit read FECodigoIFC write FECodigoIFC;
        property EDataAlterado : TMaskEdit
             read FEDataAlterado write FEDataAlterado;
        property EDataCadastro : TMaskEdit
             read FEDataCadastro write FEDataCadastro;
        property EOBS : TEdit read FEOBS write FEOBS;
        property ESituacao : TComboBox read FESituacao write FESituacao;
        property EValor : TEdit read FEValor write FEValor;
        property MaquinaIFC : Integer read GetMaquinaIFC write FMaquinaIFC;
        property OBS : String read GetOBS write FOBS;
        property Situacao : Integer read GetSituacao write FSituacao;
        property Valor : Double read GetValor write FValor;

  end;

procedure Register;

implementation

procedure Register;
begin
     { Register TFactoring with Softech as its
       default page on the Delphi component palette }
     RegisterComponents('Softech', [TFactoring]);
end;

{ Method to set variable and property values and create objects }
procedure TFactoring.AutoInitialize;
begin
     FEAgenciaNumero := nil;
     FEChequeCNC := nil;
     FECodigoFCT := nil;
     FECodigoIFC := nil;
     FEDataAlterado := nil;
     FEDataCadastro := nil;
     FEOBS := nil;
     FESituacao := nil;
     FEValor := nil;
end; { of AutoInitialize }

{ Resets prop of component type if referenced component deleted }
procedure TFactoring.Notification(AComponent : TComponent; Operation : TOperation);
begin
     inherited Notification(AComponent, Operation);
     if Operation <> opRemove then
        Exit;
     { Has a component referenced by a property of 
       this component been deleted?  If so, update 
       the property. }
     if AComponent = FEAgenciaNumero then
        FEAgenciaNumero := nil;
     if AComponent = FEChequeCNC then
        FEChequeCNC := nil;
     if AComponent = FECodigoFCT then
        FECodigoFCT := nil;
     if AComponent = FECodigoIFC then
        FECodigoIFC := nil;
     if AComponent = FEDataAlterado then
        FEDataAlterado := nil;
     if AComponent = FEDataCadastro then
        FEDataCadastro := nil;
     if AComponent = FEOBS then
        FEOBS := nil;
     if AComponent = FESituacao then
        FESituacao := nil;
     if AComponent = FEValor then
        FEValor := nil;
end;

{ Method to free any objects created by AutoInitialize }
procedure TFactoring.AutoDestroy;
begin
     { No objects from AutoInitialize to free }
end; { of AutoDestroy }

{ Read method for property AgenciaNumero }
function TFactoring.GetAgenciaNumero : String;
begin
  try
    Result := Self.fieldByName('IFC_AGENCIA_NUMERO').asString;
  except
    result:= '';
  end;
end;

{ Read method for property ChequeCNC }
function TFactoring.GetChequeCNC : Integer;
begin
  try
    Result := Self.fieldByName('CNC_CHEQUE').asInteger;
  except
    result:= 0;
  end;
end;

{ Read method for property CodigoFCT }
function TFactoring.GetCodigoFCT : Integer;
begin
  try
    Result := Self.fieldByName('FCT_CODIGO').asInteger;
  except
    result:= 0;
  end;
end;

{ Read method for property CodigoIFC }
function TFactoring.GetCodigoIFC : Integer;
begin
  try
    Result := Self.fieldByName('IFC_CODIGO').asInteger;
  except
    result:= 0;
  end;
end;

{ Read method for property DataAlterado }
function TFactoring.GetDataAlterado : TDateTime;
begin
  try
    Result := Self.fieldByName('IFC_DT_ALTERADO').asDateTime;
  except
    result:= 0;
  end;
end;

{ Read method for property DataCadastro }
function TFactoring.GetDataCadastro : TDateTime;
begin
  try
    Result := Self.fieldByName('IFC_DT_CADASTRO').asDateTime;
  except
    result:= 0;
  end;
end;

{ Read method for property MaquinaIFC }
function TFactoring.GetMaquinaIFC : Integer;
begin
  try
    Result := Self.fieldByName('FCT_MAQUINA').asInteger;
  except
    result:= 0;
  end;
end;

{ Read method for property OBS }
function TFactoring.GetOBS : String;
begin
  try
    Result := Self.fieldByName('IFC_OBSERVACAO').asString;
  except
    result:= '';
  end;
end;

{ Read method for property Situacao }
function TFactoring.GetSituacao : Integer;
begin
  try
    Result := Self.fieldByName('IFC_SITUACAO').asInteger;
  except
    result:= 0;
  end;
end;

{ Read method for property Valor }
function TFactoring.GetValor : Double;
begin
  try
    Result := Self.fieldByName('IFC_VALOR').asFloat;
  except
    result:= 0;
  end;
end;

function TFactoring.AlterarAuto:Boolean;
begin
  Result:=false;
  try
    ExecutaSQL(CConfiguracao.QueryComandos,'UPDATE '+Tabela+' SET '+
      ' CNC_ORIGEM='         +IntToStr(CentroDeCusto)+
      ',USU_CODIGO='         +IntToStr(CConfiguracao.CodigoUSU)+
      ',MCT_MAQUINA='        +IntToStr(Maquina)+
      ',IFC_DT_ALTERADO="'   +MesDiaHora(CConfiguracao.DataHora)+'" '+
      ',MCT_QUANTIDADE_CHEQUES='+EQuantidadeCheques.Text+
      ',FCT_TOTAL_ENVIADO='  +VirgPonto(ETotalEnviado.Text)+
      ',FCT_JUROS='          +VirgPonto(EJuros.Text)+
      ',FCT_TOTAL_RECEBIDO=' +VirgPonto(ETotalRecebido.Text)+
      ',FCT_OBSERVACAO="'    +EOBS.Text+'" '+
      ' WHERE CNC_CODIGO='+IntToStr(CodigoCNC)+
      ' AND FCT_CODIGO='+IntToStr(CodigoFCT));
    Result:=True;
  except
    ShowMessage('Não foi possível alterar o registro corrente. Verifique se o tipo de dado que você está tentando alterar é o mesmo do campo.');
  end;
end;

procedure TFactoring.AtualizaControles(Habilitar:Boolean);
begin
  Try
    EDbgrid.Enabled        :=not Habilitar;
  except
  end;
  try
    EClienteCNC.Enabled    := Habilitar;
  except
  end;
  try
    ECodigoCLI.Enabled     := Habilitar;
  except
  end;
  try
    EOBS.Enabled           := Habilitar;
  except
  end;
end;

procedure TFactoring.CancelaEdicao;
begin
  Estado:=0;
  AtualizaControles(False);
  if isEmpty then
    LimpaCampos
  else
    CarregaDados;
end;

procedure TFactoring.CarregaDados;
begin
  try
    ECodigoFCT.Text         := IntToStr(CodigoFCT);
  except
  end;
  try
    EClienteCNC.Text         := IntToStr(ClienteCNC);
  except
  end;
  try
    ECodigoCLI.Text          :=IntToStr(CodigoCLI);
  except
  end;
  try
    EQuantidadeCheques.Text  := IntToStr(QuantidadeCheques);
  except
  end;
  try
    ETotalRecebido.Text      :=format('%.2f',[TotalRecebido]);
  except
  end;
  try
    EJuros.Text              :=format('%.2f',[Juros]);
  except
  end;
  try
    ETotalEnviado.Text       :=format('%.2f',[TotalEnviado]);
  except
  end;
  try
    if DataCadastro > 0 then
      EDataCadastro.Text        := FormatDateTime('dd/mm/yyyy hh:mm', DataCadastro)
    else
      EDataCadastro.Clear;
  except
  end;
  try
    if DataAlterado > 0 then
      EDataAlterado.Text        := FormatDateTime('dd/mm/yyyy hh:mm', DataAlterado)
    else
      EDataCadastro.Clear;
  except
  end;
  try
    ESituacao.ItemIndex         := Situacao;
  except
  end;
  try
    EOBS.Text                   := OBS;
  except
  end;
end;

constructor TFactoring.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;
     Tabela := 'FACTORING';

     { Code to perform other tasks when the component is created }

end;

destructor TFactoring.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

function TFactoring.FinalizaEdicao:Boolean;
var
  Aux:TDataSetNotifyEvent;
  mensagem:string;
begin
  Result := False;
  mensagem:='';
  if not VerificaInteiroBranco(EClienteCNC.Text) then
    mensagem:=mensagem+'Centro de Custo de Cliente inválido!';
  if not VerificaInteiroBranco(ECodigoCLI.Text) then
    mensagem:=mensagem+'Código do Cliente inválido!';
  if not VerificaInteiroBranco(EQuantidadeCheques.Text) then
    mensagem:=mensagem+'Quantidade de Cheques inválida!';
  if not VerificaFloatBranco(ETotalEnviado.Text) then
    mensagem:=mensagem+'Total Enviado inválido!';
  if not VerificaFloatBranco(EJuros.Text) then
    mensagem:=mensagem+'Juros inválido!';
  if not VerificaFloatBranco(ETotalRecebido.Text) then
    mensagem:=mensagem+'Total Recebido inválido!';
  if mensagem <> '' then
    ShowMessage(mensagem)
  else
  Begin
    Aux:=AfterScroll;
    AfterScroll:=Nil;
    If Estado=1 then
    Begin
      If Inserirauto then
      Begin
        Result := True;
        Close;
        SQL.Text := 'SELECT * FROM '+Tabela+
          ' WHERE CNC_CODIGO='+IntToStr(CConfiguracao.CodigoCNC)+
          ' AND FCT_CODIGO='+IntToStr(SCodigo);
        Open;
        Estado:=0;
        AtualizaControles(False);
      end;
    End
    Else If Estado=2 then
    Begin
      Cod := CodigoIFC;
      If Alterarauto then
      Begin
        Result := True;
        Close;
        SQL.Text := 'SELECT * FROM '+Tabela+
          ' WHERE CNC_CODIGO='+IntToStr(CConfiguracao.CodigoCNC)+
          ' AND FCT_CODIGO='+IntToStr(Cod);
        Open;        
        Estado:=0;
        AtualizaControles(False);
      end;
    End;
    AfterScroll:=aux;
    CarregaDados;
  end;
end;

function TFactoring.InserirAuto:Boolean;
begin
  Result := False;
  try
    ExecutaSQL(CConfiguracao.QueryComandos, 'INSERT '+Tabela+
      '(CNC_ORIGEM,CNC_CODIGO,FCT_CODIGO,USU_CODIGO '+
      ',FCT_DT_CADASTRO,CNC_CLIENTE,CLI_CODIGO '+
      ',FCT_QUANTIDADE_CHEQUES '+
      ',FCT_TOTAL_ENVIADO,FCT_JUROS,FCT_TOTAL_RECEBIDO '+
      ',FCT_SITUACAO,FCT_OBSERVACAO) VALUES '+
      '( '+IntToStr(CentroDeCusto)+
      ', '+IntToStr(CConfiguracao.CodigoCNC)+
      ', '+IntToStr(SCodigo)+
      ', '+IntToStr(CConfiguracao.CodigoUSU)+
      ',"'+MesDiaHora(CConfiguracao.DataHora)+'" '+
      ', '+EClienteCNC.Text+
      ', '+ECodigoCLI.Text+
      ', '+EQuantidadeCheques.Text+
      ', '+VirgPonto(ETotalEnviado.Text)+
      ', '+VirgPonto(EJuros.Text)+
      ', '+VirgPonto(ETotalRecebido.Text)+
      ',0'+
      ',"'+EOBS.Text+'") ');
    result:=True;
  except
    ShowMessage('Não foi possível incluir o registro corrente. Verifique se o tipo de dado que você está tentando alterar é o mesmo do campo.');
  end;
end;

procedure TFactoring.LimpaCampos;
begin
  try
    if Estado <> 1 then
      ECodigoFCT.Clear;
  except
  end;
  try
    if Estado <> 1 then
      EDataCadastro.Clear
    else
      EDataCadastro.Text  := DateTimeToStr(CConfiguracao.DataHora);
  except
  end;
  try
    EDataAlterado.Clear;
  except
  end;
  try
    if CConfiguracao.Empresa <> 3 then
      EClienteCNC.Text := IntToStr(CConfiguracao.CodigoCNC)
    else
      EClienteCNC.Text := '1';
  except
  end;
  try
    ECodigoCLI.Clear;
  except
  end;
  try
    if Estado <> 1 then
      EQuantidadeCheques.Clear
    else
      EQuantidadeCheques.Text := '0';
  except
  end;
  try
    if Estado <> 1 then
      ETotalEnviado.Clear
    else
      ETotalEnviado.Text := '0,00';
  except
  end;
  try
    if Estado <> 1 then
      EJuros.Clear
    else
      EJuros.Text := '0,00';
  except
  end;
  try
    if Estado <> 1 then
      ETotalRecebido.Clear
    else
      ETotalRecebido.Text := '0,00';
  except
  end;
  try
    if Estado <> 1 then
      ESituacao.ItemIndex:=-1
    else
      ESituacao.ItemIndex:=0;
  except
  end;
  try
    EOBS.Clear;
  except
  end;
end;

{ Localiza um Grau }
function TFactoring.LocalizarCod(CdCNC,CdFCT:Integer):Boolean;
begin
  If (CdFCT<>CodigoFCT) or (CdCNC<>CodigoCNC) Then
    If locate('CNC_CODIGO;FCT_CODIGO', vararrayof([CdCNC,CdFCT]), []) Then
      Result:=True
    else
      Result:=False
  Else
    Result:=True;
end;

procedure TFactoring.PreparaAlteracao;
begin
  Estado:=2;
  AtualizaControles(True);
  try
    EDataAlterado.Text := DateTimeToStr(CConfiguracao.DataHora);
  except
  end;
end;

procedure TFactoring.PreparaInsercao;
begin
  ProximoCodigo('FCT_CODIGO');
  Estado:=1;
  AtualizaControles(True);
  LimpaCampos;
end;

function TFactoring.deletarauto:Boolean;
begin
  Result := False;
  try
    if Delete then
    Begin
      result:=true;
      if TQuery(Self).isEmpty then
        LimpaCampos;
    end;
  Except
    ShowMessage('Não foi possível deletar registro corrente!');
  End;
end;


end.
