{ ****************************************************************** }
{                                                                    }
{   VCL component TTipoParam                                         }
{                                                                    }
{   Tipo de Parâmetro da Empresa                                     }
{                                                                    }
{   Code generated by Component Create for Delphi                    }
{                                                                    }
{   Generated from source file p:\eletro guerra\classe\principal\tipoparam.cd }
{   on 22 July 1999 at 10:18                                         }
{                                                                    }
{   Copyright © 1999 by SOFTECH                                      }
{                                                                    }
{ ****************************************************************** }

unit TipoPara;

interface

uses WinTypes, WinProcs, Messages, SysUtils, Classes, Controls, 
     Forms, Graphics, Squery, Dbtables, Dialogs, Db, Stdctrls, 
     Mask, Configuracao, Dbgrids;

type
  TTipoParam = class(TSQuery)
    private
      { Private fields of TTipoParam }
        { Storage for property CodigoCNC }
        FCodigoCNC : Integer;
        { Storage for property CodigoTPR }
        FCodigoTPR : Integer;
        { Storage for property Descricao }
        FDescricao : String;
        { Storage for property ECampoLocaliz }
        FECampoLocaliz : TComboBox;
        { Storage for property ECodigoTPR }
        FECodigoTPR : TEdit;
        { Storage for property EDbgrid }
        FEDbgrid : TDBGrid;
        { Storage for property EDescricao }
        FEDescricao : TEdit;
        { Storage for property ENomeLocaliz }
        FENomeLocaliz : TEdit;

      { Private methods of TTipoParam }
        { Method to set variable and property values and create objects }
        procedure AutoInitialize;
        { Method to free any objects created by AutoInitialize }
        procedure AutoDestroy;
        { Read method for property CodigoCNC }
        function GetCodigoCNC : Integer;
        { Write method for property CodigoCNC }
        procedure SetCodigoCNC(Value : Integer);
        { Read method for property CodigoTPR }
        function GetCodigoTPR : Integer;
        { Write method for property CodigoTPR }
        procedure SetCodigoTPR(Value : Integer);
        { Read method for property Descricao }
        function GetDescricao : String;
        { Write method for property Descricao }
        procedure SetDescricao(Value : String);

    protected
      { Protected fields of TTipoParam }

      { Protected methods of TTipoParam }
        { Resets prop of component type if referenced component deleted }
        procedure Notification(AComponent : TComponent; Operation : TOperation); override;
        procedure Loaded; override;

    public
      { Public fields and properties of TTipoParam }
        { Controla o estado da entidade(0-normal,1-Inserção,2-Alteração) }
        Estado : Integer;

      { Public methods of TTipoParam }
        { Altera um Tipo de parametro }
        function Alterar(CdCNC,CdTPR: integer; PDescricao: String):boolean;
        function AlterarAuto:Boolean;
        procedure AtualizaControles(Habilitar:Boolean);
        procedure CancelaEdicao;
        procedure CarregaDados;
        constructor Create(AOwner: TComponent); override;
        procedure Deletar(CdCNC,CdTPR:Integer);
        destructor Destroy; override;
        procedure FinalizaEdicao;
        procedure Importa;
        { Insere um Tipo de parametro }
        function Inserir(CdCNC,CdTPR: integer; PDescricao: String):boolean;
        function InserirAuto:Boolean;
        function Localizar:boolean;
        { Localiza um Tipo de Parametro }
        function LocalizarCod(CdTPR,CdCNC:Integer):Boolean;
        function LocalizarNome(Nome:String):Boolean;
        procedure PreparaAlteracao;
        procedure PreparaInsercao;
        function deletarauto:Boolean;

    published
      { Published properties of TTipoParam }
        property CodigoCNC : Integer read GetCodigoCNC write SetCodigoCNC;
        { Código do Tipo de Parametro }
        property CodigoTPR : Integer read GetCodigoTPR write SetCodigoTPR;
        property Descricao : String read GetDescricao write SetDescricao;
        property ECampoLocaliz : TComboBox
             read FECampoLocaliz write FECampoLocaliz;
        property ECodigoTPR : TEdit read FECodigoTPR write FECodigoTPR;
        property EDbgrid : TDBGrid read FEDbgrid write FEDbgrid;
        property EDescricao : TEdit read FEDescricao write FEDescricao;
        property ENomeLocaliz : TEdit read FENomeLocaliz write FENomeLocaliz;

  end;

procedure Register;

implementation

procedure Register;
begin
     { Register TTipoParam with Softech as its
       default page on the Delphi component palette }
     RegisterComponents('Softech', [TTipoParam]);
end;

{ Method to set variable and property values and create objects }
procedure TTipoParam.AutoInitialize;
begin
     Estado := 0;
     FECampoLocaliz := nil;
     FECodigoTPR := nil;
     FEDbgrid := nil;
     FEDescricao := nil;
     FENomeLocaliz := nil;
end; { of AutoInitialize }

{ Resets prop of component type if referenced component deleted }
procedure TTipoParam.Notification(AComponent : TComponent; Operation : TOperation);
begin
     inherited Notification(AComponent, Operation);
     if Operation <> opRemove then
        Exit;
     { Has a component referenced by a property of 
       this component been deleted?  If so, update 
       the property. }
     if AComponent = FECampoLocaliz then
        FECampoLocaliz := nil;
     if AComponent = FECodigoTPR then
        FECodigoTPR := nil;
     if AComponent = FEDbgrid then
        FEDbgrid := nil;
     if AComponent = FEDescricao then
        FEDescricao := nil;
     if AComponent = FENomeLocaliz then
        FENomeLocaliz := nil;
end;

{ Method to free any objects created by AutoInitialize }
procedure TTipoParam.AutoDestroy;
begin
     { No objects from AutoInitialize to free }
end; { of AutoDestroy }

{ Read method for property CodigoCNC }
function TTipoParam.GetCodigoCNC : Integer;
begin
  try
    Result := Self.fieldByName('CNC_CODIGO').asInteger;
  except
    result:= 0
  end;
end;

{ Write method for property CodigoCNC }
procedure TTipoParam.SetCodigoCNC(Value : Integer);
begin
  if (Self.State=dsEdit) or (Self.State=dsInsert) then
    try
      Self.fieldByName('CNC_CODIGO').asInteger := Value;
    except
      ShowMessage('Não foi possível alterar o campo "CNC_CODIGO"!');
    end;
end;

{ Read method for property CodigoTPR }
function TTipoParam.GetCodigoTPR : Integer;
begin
  try
    Result := Self.fieldByName('TPR_CODIGO').asInteger;
  except
    result:= 0
  end;
end;

{ Write method for property CodigoTPR }
procedure TTipoParam.SetCodigoTPR(Value : Integer);
begin
  if (Self.State=dsEdit) or (Self.State=dsInsert) then
    try
      Self.fieldByName('TPR_CODIGO').asInteger := Value;
    except
      ShowMessage('Não foi possível alterar o campo "TPR_CODIGO"!');
    end;
end;

{ Read method for property Descricao }
function TTipoParam.GetDescricao : String;
begin
  try
    Result := Self.fieldByName('TPR_DESCRICAO').asString;
  except
    result:= ''
  end;
end;

{ Write method for property Descricao }
procedure TTipoParam.SetDescricao(Value : String);
begin
  if (Self.State=dsEdit) or (Self.State=dsInsert) then
  try
    Self.fieldByName('TPR_DESCRICAO').asString := Value;
  except
    ShowMessage('Não foi possível alterar o campo "TPR_DESCRICAO"!');
  end;
end;

{ Altera um Tipo de parametro }
function TTipoParam.Alterar(CdCNC,CdTPR: integer; PDescricao: String):boolean;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
  result:=true;
  If not(localizarCod(CdTPR,CdCNC)) Then
  begin
    result:=false;
    ShowMessage('Não foi possível alterar registro corrente pois o registro não existe!');
  end
  Else
  Begin
    try
      edit;
      Descricao      := PDescricao;
      try
        Post;
      except
        result:=false;
        Cancel;
        ShowMessage('Não foi possível alterar o registro corrente. Verifique se o tipo de dado que você está tentando alterar é o mesmo do campo.');
      end;
    except
      result:=false;
      ShowMessage('Não foi possível alterar registro corrente. Verifique se a tabela encontra-se em modo de somente leitura.');
    end;
  End;
end;

function TTipoParam.AlterarAuto:Boolean;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
    try
      edit;
      try
         Descricao  := EDescricao.Text;
      except
      end;
      try
        Post;
        Result:=True;
      except
        Result:=False;
        Cancel;
        ShowMessage('Não foi possível alterar o registro corrente. Verifique se o tipo de dado que você está tentando alterar é o mesmo do campo.');
      end;
    except
      Result:=false;
      ShowMessage('Não foi possível alterar registro corrente. Verifique se a tabela encontra-se em modo de somente leitura.');
    end;
end;

procedure TTipoParam.AtualizaControles(Habilitar:Boolean);
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
 Try
   EDbgrid.Enabled           :=not Habilitar;
 except
 end;
 try
   EDescricao.Enabled     :=Habilitar;
   except
 end;
end;

procedure TTipoParam.CancelaEdicao;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
  AtualizaControles(False);
  Estado:=0;
  CarregaDados;
end;

procedure TTipoParam.CarregaDados;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
 try
   ECodigoTPR.Text           :=IntToStr(CodigoTPR);
   except
 end;
 try
   EDescricao.Text           :=Descricao;
   except
 end;
end;

constructor TTipoParam.Create(AOwner: TComponent);
begin
     { Call the Create method of the parent class }
     inherited Create(AOwner);

     { AutoInitialize sets the initial values of variables and      }
     { properties; also, it creates objects for properties of       }
     { standard Delphi object types (e.g., TFont, TTimer,           }
     { TPicture) and for any variables marked as objects.           }
     { AutoInitialize method is generated by Component Create.      }
     AutoInitialize;

     { Code to perform other tasks when the component is created }

end;

procedure TTipoParam.Deletar(CdCNC,CdTPR:Integer);
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
  If not(localizarCod(CdTPR,CdCNC)) Then
    ShowMessage('Não foi possível deletar registro corrente pois o registro não existe!')
  Else
  Begin
    try
      Delete;
    Except
      ShowMessage('Não foi possível deletar registro corrente!');
    End;
  End;
end;

destructor TTipoParam.Destroy;
begin
     { AutoDestroy, which is generated by Component Create, frees any   }
     { objects created by AutoInitialize.                               }
     AutoDestroy;

     { Here, free any other dynamic objects that the component methods  }
     { created but have not yet freed.  Also perform any other clean-up }
     { operations needed before the component is destroyed.             }

     { Last, free the component by calling the Destroy method of the    }
     { parent class.                                                    }
     inherited Destroy;
end;

procedure TTipoParam.FinalizaEdicao;
     { Internal declarations for method }
     { type }
     { . . . }
var
  cod, cdcnc:Integer;
begin
  If Estado=1 then
  Begin
    Inserirauto;
    close;
    open;
  End;

  If Estado=2 then
  Begin
    cod:=codigoTPR;
    cdcnc:=codigoCNC;
    Alterarauto;
    close;
    open;
    LocalizarCod(cod, cdcnc);
  End;

  AtualizaControles(False);
  Estado:=0;
end;

procedure TTipoParam.Importa;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
 with CTransfArq do
  begin
    SelecionaTipo(26, date);
    while not eof do
    begin
      if Metodo='01' then
        with TTipoParam(ImportComponent) do
        begin
          Self.Inserir(CodigoCNC,CodigoTPR,Descricao);
        end;
      if Metodo='02' then
        with TTipoParam(ImportComponent) do
        begin
          Self.Alterar(CodigoCNC,CodigoTPR,Descricao);
        end;
      if Metodo='03' then
        with TTipoParam(ImportComponent) do
        begin
          Self.Deletar(CodigoCNC,CodigoTPR);
        end;
      next;
    end;
  end;

end;

{ Insere um Tipo de parametro }
function TTipoParam.Inserir(CdCNC,CdTPR: integer; PDescricao: String):boolean;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
  result := true;
  Insert;
  if CdTPR=0 then
    CodigoTPR    := ProximoCodigo('TPR_CODIGO')
  else
    CodigoTPR    := CdTPR;
  try
    CodigoCNC      := CdCNC;
    Descricao      := PDescricao;

    try
      Post;
    except
      result:=false;
      Cancel;
      ShowMessage('Não foi possível incluir o registro corrente! Verifique se o tipo de dado a ser inserido é igual ao do campo.');
    end;
  except
    result:=false;
    ShowMessage('Não foi possível incluir o registro! Verifique se a tabela encontra-se em modo de somente leitura.');
  end;
end;

function TTipoParam.InserirAuto:Boolean;
     { Internal declarations for method }
     { type }
     { . . . }
Var
  Aux:TDataSetNotifyEvent;
begin
    try
      Aux:=AfterScroll;
      AfterScroll:=Nil;
      append;.
      try
        CodigoTPR   := SCodigo;
      except
      end;
      try
        codigocnc   := 0;
      except
      end;
      try
         Descricao  := EDescricao.Text;
      except
      end;
      try
        Post;
        AfterScroll:=aux;
        CarregaDados;
        result:=True;
      except
        result:=False;
        Cancel;
        ShowMessage('Não foi possível incluir o registro corrente. Verifique se o tipo de dado que você está tentando alterar é o mesmo do campo.');
      end;
    except
      result:=false;
      ShowMessage('Não foi possível alterar registro corrente. Verifique se a tabela encontra-se em modo de somente leitura.');
    end;
end;

procedure TTipoParam.Loaded;
begin
     inherited Loaded;

     { Perform any component setup that depends on the property
       values having been set }

end;

function TTipoParam.Localizar:boolean;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
Var
  Campo,Nome,campoloc:String;
  i         :Integer;
begin
  If (ECampoLocaliz.Text<>'') and (ENomeLocaliz.text<>'') Then
  Begin
    try
      campoloc:=trim(ECampoLocaliz.Text);
      for i:= length(campoloc) downto 1 do
        If campoloc[i]=' ' Then
        Begin
          Campo := Copy(campoloc,i+1,length(campoloc)-i);
          Break;
        End;
    except
    end;
    try
      Nome:=Trim(ENomeLocaliz.text);
    except
    end;
    If locate(campo,Nome, [loCaseInsensitive]) Then
      Result:=True
    else
      Result:=False;
  End;
end;

{ Localiza um Tipo de Parametro }
function TTipoParam.LocalizarCod(CdTPR,CdCNC:Integer):Boolean;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
  If (CdTPR<>CodigoTPR) or (CdCNC<>CodigoCNC) Then
    If locate('CNC_CODIGO;TPR_CODIGO', vararrayof([CdCNC, CdTPR]), []) Then
      Result:=True
    else
      Result:=False
  Else
    Result:=True;
end;

function TTipoParam.LocalizarNome(Nome:String):Boolean;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
  If Nome<>Descricao Then
    If locate('TPR_DESCRICAO',Nome, []) Then
      Result:=True
    else
      Result:=False
  Else
    Result:=True;
end;

procedure TTipoParam.PreparaAlteracao;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
  AtualizaControles(True);
  Estado:=2;
end;

procedure TTipoParam.PreparaInsercao;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
ProximoCodigo('TPR_CODIGO');
 try
   EDescricao.Clear;
   except
 end;
  AtualizaControles(True);
  Estado:=1;
end;

function TTipoParam.deletarauto:Boolean;
     { Internal declarations for method }
     { type }
     { . . . }
     { var }
     { . . . }
begin
  try
    Delete;
  Except
    Result:=False;
    ShowMessage('Não foi possível deletar registro corrente!');
  End;
end;


end.
