
//Banco de dados do projetoda portaria hospedado no HOSTED
//Data Source=70.38.11.27;
//User ID=lagoa
//User ID=admin
//User ID=buildsis
//Password=agfm1901
//para
//Password=agfm1707
//Banco: buildsis_lagoa


{
DROP TABLE CONDOMINIO;
CREATE TABLE CONDOMINIO (
  ID INTEGER IDENTITY (1,1) NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  ATIVO VARCHAR(3) NOT NULL, /*SIM ou NÃO*/
  CNPJ VARCHAR(14),
  SINDICO_NOME VARCHAR(50),
  SINDICO_FONE VARCHAR(20));
INSERT INTO CONDOMINIO (NOME, ATIVO, CNPJ, SINDICO_NOME, SINDICO_FONE) VALUES
  ('LAGOA JÓQUEI VILLE', 'SIM', '22996271000181', 'ANDERSON GONÇALVES', '85997017055');

DROP TABLE RESERVAVEL;
CREATE TABLE RESERVAVEL (
  ID INTEGER IDENTITY (1,1) NOT NULL,
  ID_CONDOMINIO INTEGER NOT NULL,
  DESCRICAO VARCHAR(50) NOT NULL,
  ATIVO VARCHAR(3) NOT NULL); /*SIM ou NÃO*/
INSERT INTO RESERVAVEL (ID_CONDOMINIO, DESCRICAO, ATIVO) VALUES
  (1, 'DECK', 'SIM');

DROP TABLE APARTAMENTO;
CREATE TABLE APARTAMENTO (
  ID INTEGER IDENTITY (1,1) NOT NULL,
  ID_CONDOMINIO INTEGER NOT NULL,
  BLOCO VARCHAR(4),
  NUMERO VARCHAR(6) NOT NULL,
  NOME_COELCE VARCHAR(50),
  CPF_COELCE VARCHAR(14),
  OBSERVACAO TEXT);

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0101')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0102')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0103')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0105')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0107')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0108')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0201')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0202')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0203')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0204')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0205')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0206')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0207')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0208')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0301')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0302')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0303')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0304')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0305')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0306')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0307')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0308')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0401')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0402')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0403')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0404')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0405')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0406')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0407')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0408')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0501')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0502')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0503')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0504')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0505')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0506')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0507')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0508')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0601')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0602')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0603')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0604')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0605')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0606')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0607')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0608')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0701')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0702')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0703')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0704')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0705')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0706')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0707')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0708')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0801')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0802')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0803')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0804')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0805')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0806')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0807')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0808')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0901')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0902')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0903')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0904')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0905')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0906')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0907')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '0908')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1001')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1002')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1003')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1004')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1005')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1006')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1007')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1008')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1101')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1102')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1103')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1104')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1105')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1106')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1107')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1108')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1201')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1202')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1203')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1204')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1205')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1206')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1207')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'A', '1208')




INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0101')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0102')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0103')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0105')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0107')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0108')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0201')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0202')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0203')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0204')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0205')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0206')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0207')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0208')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0301')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0302')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0303')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0304')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0305')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0306')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0307')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0308')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0401')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0402')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0403')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0404')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0405')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0406')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0407')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0408')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0501')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0502')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0503')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0504')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0505')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0506')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0507')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0508')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0601')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0602')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0603')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0604')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0605')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0606')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0607')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0608')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0701')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0702')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0703')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0704')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0705')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0706')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0707')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0708')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0801')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0802')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0803')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0804')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0805')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0806')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0807')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0808')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0901')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0902')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0903')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0904')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0905')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0906')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0907')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '0908')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1001')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1002')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1003')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1004')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1005')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1006')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1007')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1008')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1101')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1102')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1103')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1104')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1105')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1106')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1107')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1108')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1201')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1202')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1203')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1204')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1205')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1206')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1207')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'B', '1208')



INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0101')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0102')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0103')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0105')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0107')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0108')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0201')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0202')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0203')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0204')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0205')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0206')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0207')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0208')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0301')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0302')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0303')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0304')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0305')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0306')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0307')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0308')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0401')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0402')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0403')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0404')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0405')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0406')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0407')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0408')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0501')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0502')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0503')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0504')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0505')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0506')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0507')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0508')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0601')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0602')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0603')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0604')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0605')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0606')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0607')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0608')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0701')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0702')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0703')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0704')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0705')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0706')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0707')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0708')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0801')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0802')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0803')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0804')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0805')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0806')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0807')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0808')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0901')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0902')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0903')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0904')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0905')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0906')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0907')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '0908')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1001')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1002')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1003')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1004')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1005')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1006')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1007')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1008')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1101')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1102')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1103')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1104')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1105')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1106')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1107')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1108')

INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1201')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1202')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1203')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1204')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1205')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1206')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1207')
INSERT INTO APARTAMENTO (ID_CONDOMINIO, BLOCO, NUMERO) VALUES (1, 'C', '1208')

DROP TABLE MORADOR;
CREATE TABLE MORADOR (
  ID INTEGER IDENTITY (1,1) NOT NULL,
  ID_CONDOMINIO INTEGER NOT NULL,
  ID_APARTAMENTO INTEGER NOT NULL,
  TIPO_MORADOR VARCHAR(20) NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  FONE VARCHAR(20),
  CPF VARCHAR(11),
  RG VARCHAR(20),
  PROFISSAO VARCHAR(50),
  OBSERVACAO TEXT)

DROP TABLE USUARIO;
CREATE TABLE USUARIO (
  ID INTEGER IDENTITY (1,1) NOT NULL,
  ID_CONDOMINIO INTEGER NOT NULL,
  ID_APARTAMENTO INTEGER,
  TIPO_USUARIO VARCHAR(25) NOT NULL, /*(1,'MORADOR') / (2,'SINDICO') / (3,'CONSELHEIRO') / (4,'ADMINISTRADOR') / (5,'PORTEIRO') / (6,'SEGURANÇA') / (7,'ZELADOR') / (8,'JARDINEIRO')*/
  MORADOR VARCHAR(3) NOT NULL, /*SIM ou NÃO*/
  ATIVO VARCHAR(3) NOT NULL, /*SIM ou NÃO*/
  NOME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL, /*UTILIZADO PARA FAZER O LOGIN*/
  SENHA VARCHAR(50) NOT NULL);
INSERT INTO USUARIO (ID_CONDOMINIO, ID_APARTAMENTO, TIPO_USUARIO, MORADOR, ATIVO, NOME, EMAIL, SENHA )
VALUES (1, 44, 'SINDICO', 'SIM', 'SIM', 'ANDERSON GONÇALVES', 'anndersonn.gonncalves@gmail.com', '1707')
INSERT INTO USUARIO (ID_CONDOMINIO, TIPO_USUARIO, MORADOR, ATIVO, NOME, EMAIL, SENHA )
VALUES (1, 'ADMINISTRADOR', 'NÃO', 'SIM', 'RAIMUNDO', 'admlagoajoqueiville@gmail.com', '1234')

DROP TABLE OCORRENCIA;
CREATE TABLE OCORRENCIA (
  ID INTEGER IDENTITY (1,1) NOT NULL,
  ID_CONDOMINIO INTEGER NOT NULL,
  ID_USUARIO INTEGER NOT NULL,
  NOME_USUARIO VARCHAR(50) NOT NULL,
  IMPORTANTE VARCHAR(3) NOT NULL, /*SIM ou NÃO*/
  DATA_REGISTRO DATETIME NOT NULL,
  DATA_OCORRENCIA DATETIME NOT NULL,
  DESCRICAO TEXT NOT NULL,
  ASSINADA VARCHAR(3) NOT NULL, /*SIM ou NÃO*/
  DIRECIONAMENTO TEXT NOT NULL);

DROP TABLE RESERVA;
CREATE TABLE RESERVA (
  ID INTEGER IDENTITY (1,1) NOT NULL,
  ID_CONDOMINIO INTEGER NOT NULL,  
  ID_APARTAMENTO INTEGER NOT NULL,
  ID_USUARIO INTEGER NOT NULL,
  ID_RESERVAVEL INTEGER NOT NULL,  
  DESCRICAO VARCHAR(255),
  RESPONSAVEL VARCHAR(50) NOT NULL,
  STATUS VARCHAR(1) NOT NULL, /**/
  DATA_SOLICITACAO DATETIME NOT NULL,
  DATA_EVENTO DATETIME NOT NULL,
  DATA_CANCELAMENTO DATETIME,
  EFETUAR_COBRANCA VARCHAR(3) NOT NULL); /*SIM ou NÃO*/
}

unit uMenu;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, ActnList, XPStyleActnCtrls, ActnMan, ToolWin, ActnCtrls, StrUtils,
  ActnMenus, ComCtrls, jpeg, ExtCtrls, StdCtrls, uVariaveis, mscorlib_TLB, SiacReport_TLB;


type
  TfrmMenu = class(TForm)
    ActionManager1: TActionManager;
    AR_MudarUsuario: TAction;
    AJ_Ajuda: TAction;
    AR_AlterarSenha: TAction;
    AR_Sair: TAction;
    AJ_Sobre: TAction;
    AC_SQL: TAction;
    AC_Backup: TAction;
    AJ_AtualizarSistema: TAction;
    AC_BlocoNotas: TAction;
    AC_Calendario: TAction;
    AC_Calculadora: TAction;
    PR_LivroOcorrencia: TAction;
    ActionMainMenuBar1: TActionMainMenuBar;
    sbMenu: TStatusBar;
    Image1: TImage;
    PR_Reserva: TAction;
    PR_Morador: TAction;
    ToolBar1: TToolBar;
    tbMoradores: TToolButton;
    tbReserva: TToolButton;
    tbLivroDeOcorrencia: TToolButton;
    ToolButton1: TToolButton;
    tbTermo: TToolButton;
    ToolButton3: TToolButton;
    procedure PR_LivroOcorrenciaExecute(Sender: TObject);
    procedure AR_MudarUsuarioExecute(Sender: TObject);
    procedure FormActivate(Sender: TObject);
    procedure PR_ReservaExecute(Sender: TObject);
    procedure PR_MoradorExecute(Sender: TObject);
    procedure tbTermoClick(Sender: TObject);
  private
    { Private declarations }
    procedure ShowTela(Tela: TForm);
    procedure IdentificaUsuario;
  public
  end;

var
  frmMenu: TfrmMenu;

procedure EnviaEmail(aPorteiro, aData, aHora, aMensagem: string; aImportante: boolean; aAnexos: ArrayList);

implementation

uses uLivro, uLogin, uReserva;

{$R *.dfm}

procedure TfrmMenu.ShowTela(Tela: TForm);
begin
  Tela.Left := 1;
  Tela.Top := 1;
  Tela.Show;
end;

procedure TfrmMenu.PR_LivroOcorrenciaExecute(Sender: TObject);
begin
  Application.CreateForm(TfrmLivro, frmLivro);
  ShowTela(frmLivro);
end;

procedure TfrmMenu.AR_MudarUsuarioExecute(Sender: TObject);
begin
  Application.CreateForm(TfrmLogin, frmLogin);
  try
    frmLogin.ShowModal;
    IdentificaUsuario;
  finally
    FreeAndNil(frmLogin);
  end;
end;

procedure TfrmMenu.FormActivate(Sender: TObject);
begin
  IdentificaUsuario;
end;

procedure TfrmMenu.IdentificaUsuario;
begin
  sbMenu.Panels[2].Text := NomeUsuarioLogado;
  sbMenu.Panels[3].Text := FormatDateTime('"Fortaleza-CE, " dd " de " mmmm " de " yyyy', now);
end;

procedure EnviaEmail(aPorteiro, aData, aHora, aMensagem: string; aImportante: boolean; aAnexos: ArrayList);
var
  msgOcorrencia: string;
  stiReport: CoSiacReport_; //TSiacReport;
const
  cImportante = ' (IMPORTANTE)';
begin
  msgOcorrencia := 'Porteiro: ' + aPorteiro + IfThen(aImportante, cImportante, '') + '<br/>' +
                   'Data: ' + aData + '<br/>' +
                   'Hora: ' + aHora + '<br/><br/>' +
                   aMensagem;
  {
  IdSMTP1.Port               := 25;
  IdSMTP1.Host               := 'aspmx.l.google.com'; //aspmx.l.google.com ou smtp.gmail.com
  IdSMTP1.Username           := 'admlagoajoqueiville@gmail.com';
  IdSMTP1.Password           := '17072007';
  IdSMTP1.AuthenticationType := atLogin; //atNone;

  //Prioridade alta
  IdMessage1.Priority := mpLow;
  //'Email_originário_da_mensagem';
  IdMessage1.From.Address := 'admlagoajoqueiville@gmail.com';
  //'Email_do_destinatario_da_mensagem';
  IdMessage1.Recipients.EMailAddresses := 'anndersonn.gonncalves@gmail.com'; //'seu_mail_aqui';
  //O assunto da mensagem
  IdMessage1.Subject :='Livro de ocorrência';
  //conteudo da mensagem
  IdMessage1.Body.Add(msgOcorrencia);
  //Tratando os arquivos anexos
  for i := 0 to mmAnexos.Lines.Count-1 do
    TIdAttachment.create(Idmessage1.MessageParts, TFileName(mmAnexos.Lines.Strings[i]));
  try
    IdSMTP1.Connect;
    IdSMTP1.Send(IdMessage1);
  finally
    IdSMTP1.Disconnect;
  end;
  }

  //Do email da portario: outlook para gmail e outlook
  stiReport.Create.SendMessage('smtp.live.com',
                               'portarialagoajoqueiville@outlook.com',
                               'Portaria',
                               'P17072007',
                               'anndersonn.gonncalves@gmail.com',
                               'Síndico',
                               'anndersonn.gonncalves@outlook.com',
                               'Livro de ocorrência',
                               msgOcorrencia,
                               aAnexos);

  //Do email da portario GMAIL
  {stiReport.Create.SendMessage('aspmx.l.google.com',
                               'admlagoajoqueiville@gmail.com',
                               'Portaria',
                               '17072007',
                               'anndersonn.gonncalves@gmail.com',
                               'Síndico',
                               'anndersonn.gonncalves@outlook.com',
                               'Livro de ocorrência',
                               msgOcorrencia,
                               aAnexos);}


  //Do email Outlook para GMAIL
  {stiReport.Create.SendMessage('smtp.live.com',
                               'anndersonn.gonncalves@outlook.com',
                               'Portaria',
                               '@gfm1901',
                               'anndersonn.gonncalves@gmail.com',
                               'Síndico',
                               'anndersonn.gonncalves@gmail.com',
                               'Livro de ocorrência',
                               msgOcorrencia,
                               aAnexos);             }

  //Do email Outlook para Outlook
  {stiReport.Create.SendMessage('smtp.live.com',
                               'anndersonn.gonncalves@outlook.com',
                               'Portaria',
                               '@gfm1901',
                               'anndersonn.gonncalves@outlook.com',
                               'Síndico',
                               'anndersonn.gonncalves@outlook.com',
                               'Livro de ocorrência',
                               msgOcorrencia,
                               aAnexos);}
end;

procedure TfrmMenu.PR_ReservaExecute(Sender: TObject);
begin
  Application.CreateForm(TfrmReserva, frmReserva);
  ShowTela(frmReserva);
end;

procedure TfrmMenu.PR_MoradorExecute(Sender: TObject);
begin
  //todo:
  showmessage('Em desenvolvimento!');
end;

procedure TfrmMenu.tbTermoClick(Sender: TObject);
var
  stiReport: CoSiacReport_;
  SQL: string;
  rptArquivoLogoLagoa: string;
begin
  if fileexists('logo-lagoa.bmp') then
    rptArquivoLogoLagoa := 'logo-lagoa.bmp'
  else if fileexists('logo-lagoa.jpg') then
    rptArquivoLogoLagoa := 'logo-lagoa.jpg'
  else if fileexists('logo-lagoa.png') then
    rptArquivoLogoLagoa := 'logo-lagoa.png'
  else
    rptArquivoLogoLagoa := '';

  SQL := 'SELECT * FROM EVENTOS WHERE ID = 1';
  stiReport.Create.ReportLagoaTermoReserva(false,
                                           false,
                                           SQL,
                                           EnderecoCondominio,
                                           '',//Termo de reserva do Deck
                                           '',//Empresa
                                           NomeCondominio,//DM.Configuracao1.LojaNome
                                           'TERMO DE RESPONSABILIDADE',
                                           '',//NOME DO USUARIO
                                           '',//Filtros
                                           rptArquivoLogoLagoa);
end;

end.
